### ISSUE TITLE
Question about the parameters in the kernel

### ISSUE THREAD

**Issue by zjin-lcf** [rsrice/gpa-minimod-artifacts#2]
I have a few questions about the kernel parameters.

```
#define N_RADIUS 4
#define N_THREADS_PER_BLOCK_DIM 8

__global__ void target_inner_3d_kernel(
```

Does N_RADIUS  depend on N_THREADS_PER_BLOCK_DIM  ?

Can you specify which need to be changed in the kernel when the number of threads per dimension is not the same (e.g. 8,8,4) for the three dimensions ? 

Thanks

**Comment by Jokeren** [comment]
`N_RADIUS` does not depend on `N_THREADS_PER_BLOCK_DIM`. `N_RADIUS = 4` refers to the case which the *order* of a stencil is high. Figure 1 in this paper (https://arxiv.org/ftp/arxiv/papers/2002/2002.05983.pdf) shows the comparison between a low order stencil and a high order stencil. Usually we use the same number for all three dimensions. @rsrice can provide more information.

**Comment by zjin-lcf** [comment]
When N_THREADS_PER_BLOCK_DIM is equal to 4, the min and max values are 0.  If you could reproduce that, please suggest the code changes. I assume min and max values are not supposed to be 0.   

```
./main --grid 100
ndamp = 27 27 27
grid = 100 100 100
time step 100 / 1000
time step 200 / 1000
time step 300 / 1000
time step 400 / 1000
time step 500 / 1000
time step 600 / 1000
time step 700 / 1000
time step 800 / 1000
time step 900 / 1000
time step 1000 / 1000
FINAL min_u,  max_u = 0.000000, 0.000000
```

**Comment by sairyuichi** [comment]
`N_THREADS_PER_BLOCK_DIM` and `N_RADIUS` in this implementation are **not** parameters. The optimizations of shared memory fetching, such as L40-45, assume the grid size of 8x8x8 as we have discussed in this paper (https://arxiv.org/abs/2009.04619). They are not parameters but are extracted out as macros for better readability instead of magic numbers being all over the place.

With that said, we are working towards a semi-automated code generation for `minimod` that allows the arbitrary grid sizes. It also implies one can specify different sizes across three dimensions. If you are interested in `minimod` and plan to experimenting different grid sizes, such as `8x8x4` or `7x5x6`, please stay tuned.
